name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'
  workflow_dispatch:

jobs:
  tests-on-linux:
    name: Tests on Linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev libpython3-dev libxml2-dev libncurses-dev libz3-dev pkg-config zlib1g-dev
      - name: Install Swift
        run: |
          curl -O "https://download.swift.org/swiftly/linux/swiftly-1.1.1-x86_64.tar.gz"
          tar -zxf swiftly-1.1.1-x86_64.tar.gz
          SWIFTLY_HOME_DIR=$HOME/.swiftly SWIFTLY_BIN_DIR=$HOME/.swiftly/bin ./swiftly init --assume-yes --skip-install
          . "$HOME/.swiftly/env.sh"
          swiftly install 6.2.4 --use
      - name: Swift version
        run: . "$HOME/.swiftly/env.sh" && swift --version
      - name: Run tests
        run: . "$HOME/.swiftly/env.sh" && make test
      # - name: Lint
      #   run: ./lint.sh

  tests-on-mac:
    name: Tests on macOS
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Run tests
        run: make test
      # - name: Lint
      #   run: ./lint.sh
      - name: Xcode build
        run: |
          xcodebuild -scheme Bocho -destination "platform=macOS" -configuration Debug -enableCodeCoverage YES test
      - uses: codecov/codecov-action@v4
