name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  tests-on-linux:
    name: Tests on Linux
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          swiftenv install 5.5.2
          swiftenv global 5.5.2
      - run: swift --version
      - run: make test
      - run: ./lint.sh
  tests-on-mac:
    name: Tests on macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: make test
      - run: ./lint.sh
      - run: |
          make xcodegen
          xcodebuild -project bocho.xcodeproj -scheme bocho-Package clean
          xcodebuild -project bocho.xcodeproj -scheme bocho-Package -sdk macosx12.1 -destination arch=x86_64 -configuration Debug -enableCodeCoverage YES test
      - uses: codecov/codecov-action@v1.2.1
